### PR TITLE
Bare-bones block placement

### PR DESCRIPTION
**Pull request by QiZD90**
Implemented a bare-bones block placement, tried to unify a codestyle: removed stray tabs, shortened long lines etc, changed large inner switches to if-else chains, changed controls.

### CODE REVIEW

**Comment by LaG1924** [comment]
Good job.  But it does not compile under Visual Studio because of the conflict between std::min and macro min (defined in Windows.h) on the line GameState.cpp:606.

**Comment by QiZD90** [comment]
I tried a little hack, but I'm not sure it will work.

**Comment by LaG1924** [comment]
Ok, it's working now. But still it's hack. I think it will be better to defile NOMINMAX before including the header, or even add it to the CMake file as a special workaround for Windows.

**Comment by QiZD90** [comment]
I created variadic min/max functions with prefixed by underscore names because `min` and `max` macros could be defined in other platforms different from Windows and then code will be flooded by platform-specific rules for various OSes.

**Comment by LaG1924** [comment]
Well, this is also a good solution. But still, I do not think that the conflict between the standard library and platform-dependent libraries is often enough to worry about.

Thank you for your contribution.

**Pull request merged**
